version: "3.8"

services:
  db:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3307:3307"
    volumes:
      - db:/var/lib/mysql
  server:
    build:
      context: ./server
      dockerfile: server.dockerfile
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD"
      }'
    ports:
      - "8080:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true
  client:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      PORT: 4000
      PROXY_API: http://proxy:$NGINX_PROXY_PORT/
    ports:
      - "4000:4000"
    command: npm run serve
    depends_on:
      - server
  proxy:
    image: nginx:1.23
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - client
volumes:
  db:
  proxy: