version: "3.8"

services:
  db:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3307:3307"
  server:
    build:
      context: ./server
      dockerfile: server.dockerfile
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - "8080:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true
  client:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      PORT: 4000
      PROXY_API: http://server:$SPRING_DOCKER_PORT/
    ports:
      - "4000:4000"
    command: npm run serve
    depends_on:
      - server